name: Sync Fork

on:
  schedule:
    - cron: '0 15 * * 5'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: tgymnich/fork-sync@v1
        with:
          owner: CorentinTh
          base: main
          head: main
          merge_method: rebase
